export const aiScripting = {
  label: "Ai脚本开发",
  link: "ai-scripting/introduction/whatisscripting",
  icon: "open-book",
  items: [
    {
      label: "Introduction",
      translations: { "zh-CN": "介绍" },
      items: [
        {
          label: "WhatIsScripting",
          link: "/ai-scripting/introduction/whatisscripting",
          translations: { "zh-CN": "什么是脚本开发" },
        },
        {
          label: "Changelog",
          link: "/ai-scripting/introduction/changelog",
          translations: { "zh-CN": "更新日志" },
        },
        {
          label: "ScriptingLanguageSupport",
          link: "/ai-scripting/introduction/scriptinglanguagesupport",
          translations: { "zh-CN": "脚本语言支持" },
        },
        {
          label: "ViewingTheObjectModel",
          link: "/ai-scripting/introduction/viewingtheobjectmodel",
          translations: { "zh-CN": "查看对象模型" },
        },
        {
          label: "ExecutingScripts",
          link: "/ai-scripting/introduction/executingscripts",
          translations: { "zh-CN": "执行脚本" },
        },
      ],
    },
    {
      label: "Illustrator Scripting Object Model",
      translations: { "zh-CN": "Illustrator 脚本对象模型" },
      items: [
        {
          label: "ObjectModel",
          link: "/ai-scripting/objectmodel/objectmodel",
        },
        {
          label: "ObjectNamingConventions",
          link: "/ai-scripting/objectmodel/objectnamingconventions",
          translations: { "zh-CN": "对象命名规范" },
        },
        {
          label: "TopLevelObjects",
          link: "/ai-scripting/objectmodel/toplevelobjects",
          translations: { "zh-CN": "顶层对象" },
        },
        {
          label: "TheArtworkTree",
          link: "/ai-scripting/objectmodel/theartworktree",
          translations: { "zh-CN": "图稿树结构" },
        },
        {
          label: "TextObjects",
          link: "/ai-scripting/objectmodel/textobjects",
          translations: { "zh-CN": "文本对象" },
        },
        {
          label: "Dynamic",
          link: "/ai-scripting/objectmodel/dynamic",
          translations: { "zh-CN": "动态对象" },
        },
        {
          label: "Symbols",
          link: "/ai-scripting/objectmodel/symbols",
          translations: { "zh-CN": "符号" },
        },
        {
          label: "Transformations",
          link: "/ai-scripting/objectmodel/transformations",
          translations: { "zh-CN": "变换操作" },
        },
      ],
    },
    {
      label: "Scripting Illustrator",
      translations: { "zh-CN": "Illustrator 脚本开发" },
      items: [
        {
          label: "Launching",
          link: "/ai-scripting/scripting/launching",
          translations: { "zh-CN": "启动控制" },
        },
        {
          label: "WorkingWithObjects",
          link: "/ai-scripting/scripting/workingwithobjects",
          translations: { "zh-CN": "对象操作" },
        },
        {
          label: "MeasurementUnits",
          link: "/ai-scripting/scripting/measurementunits",
          translations: { "zh-CN": "测量单位" },
        },
        {
          label: "Positioning",
          link: "/ai-scripting/scripting/positioning",
          translations: { "zh-CN": "定位系统" },
        },
        {
          label: "PathsShapes",
          link: "/ai-scripting/scripting/pathsshapes",
          translations: { "zh-CN": "路径与形状" },
        },
        {
          label: "UserInteractionLevels",
          link: "/ai-scripting/scripting/userinteractionlevels",
          translations: { "zh-CN": "用户交互级别" },
        },
        {
          label: "PrintingDocuments",
          link: "/ai-scripting/scripting/printingdocuments",
          translations: { "zh-CN": "文档打印" },
        },
      ],
    },
    {
      label: "Scripting with AppleScript",
      translations: { "zh-CN": "使用 AppleScript 开发" },
      items: [
        {
          label: "ForMoreInfo",
          link: "/ai-scripting/scriptingapplescript/formoreinfo",
          translations: { "zh-CN": "更多信息" },
        },
        {
          label: "YourFirstScript",
          link: "/ai-scripting/scriptingapplescript/yourfirstscript",
          translations: { "zh-CN": "第一个脚本" },
        },
        {
          label: "ObjectReferences",
          link: "/ai-scripting/scriptingapplescript/objectreferences",
          translations: { "zh-CN": "对象引用" },
        },
        {
          label: "WorkingWithTextFrames",
          link: "/ai-scripting/scriptingapplescript/workingwithtextframes",
          translations: { "zh-CN": "文本框操作" },
        },
        {
          label: "CreatingPathsShapes",
          link: "/ai-scripting/scriptingapplescript/creatingpathsshapes",
          translations: { "zh-CN": "创建路径形状" },
        },
        {
          label: "PerspectiveGrid",
          link: "/ai-scripting/scriptingapplescript/perspectivegrid",
          translations: { "zh-CN": "透视网格" },
        },
      ],
    },
    {
      label: "Scripting with JavaScript",
      translations: { "zh-CN": "使用 JavaScript 开发" },
      items: [
        {
          label: "ForMoreInfo",
          link: "/ai-scripting/scriptingjavascript/formoreinfo",
          translations: { "zh-CN": "更多信息" },
        },
        {
          label: "YourFirstScript",
          link: "/ai-scripting/scriptingjavascript/yourfirstscript",
          translations: { "zh-CN": "第一个脚本" },
        },
        {
          label: "WorkingWithMethods",
          link: "/ai-scripting/scriptingjavascript/workingwithmethods",
          translations: { "zh-CN": "方法操作" },
        },
        {
          label: "ObjectReferences",
          link: "/ai-scripting/scriptingjavascript/objectreferences",
          translations: { "zh-CN": "对象引用" },
        },
        {
          label: "WorkingWithTextFrames",
          link: "/ai-scripting/scriptingjavascript/workingwithtextframes",
          translations: { "zh-CN": "文本框操作" },
        },
        {
          label: "CreatingPathsShapes",
          link: "/ai-scripting/scriptingjavascript/creatingpathsshapes",
          translations: { "zh-CN": "创建路径形状" },
        },
        {
          label: "PerspectiveGrid",
          link: "/ai-scripting/scriptingjavascript/perspectivegrid",
          translations: { "zh-CN": "透视网格" },
        },
      ],
    },
    {
      label: "Scripting with VBScript",
      translations: { "zh-CN": "使用 VBScript 开发" },
      items: [
        {
          label: "ForMoreInfo",
          link: "/ai-scripting/scriptingvbscript/formoreinfo",
          translations: { "zh-CN": "更多信息" },
        },
        {
          label: "YourFirstScript",
          link: "/ai-scripting/scriptingvbscript/yourfirstscript",
          translations: { "zh-CN": "第一个脚本" },
        },
        {
          label: "ObjectReferences",
          link: "/ai-scripting/scriptingvbscript/objectreferences",
          translations: { "zh-CN": "对象引用" },
        },
        {
          label: "WorkingWithTextFrames",
          link: "/ai-scripting/scriptingvbscript/workingwithtextframes",
          translations: { "zh-CN": "文本框操作" },
        },
        {
          label: "CreatingPathsShapes",
          link: "/ai-scripting/scriptingvbscript/creatingpathsshapes",
          translations: { "zh-CN": "创建路径形状" },
        },
        {
          label: "EnumerationValues",
          link: "/ai-scripting/scriptingvbscript/enumerationvalues",
          translations: { "zh-CN": "枚举值" },
        },
        {
          label: "PerspectiveGrid",
          link: "/ai-scripting/scriptingvbscript/perspectivegrid",
          translations: { "zh-CN": "透视网格" },
        },
      ],
    },
    {
      label: "Javascript Object Reference",
      translations: { "zh-CN": "JavaScript 对象参考" },
      items: [
        {
          label: "ScriptingConstants",
          link: "/ai-scripting/jsobjref/scripting-constants",
          translations: { "zh-CN": "脚本常量" },
        },
        {
          label: "JavaScriptObjectReference",
          link: "/ai-scripting/jsobjref/javascript-object-reference",
        },
        { label: "Application", link: "/ai-scripting/jsobjref/application" },
        { label: "Artboard", link: "/ai-scripting/jsobjref/artboard" },
        { label: "Artboards", link: "/ai-scripting/jsobjref/artboards" },
        { label: "Brush", link: "/ai-scripting/jsobjref/brush" },
        { label: "Brushes", link: "/ai-scripting/jsobjref/brushes" },
        {
          label: "CharacterAttributes",
          link: "/ai-scripting/jsobjref/characterattributes",
        },
        { label: "Characters", link: "/ai-scripting/jsobjref/characters" },
        { label: "CharacterStyle", link: "/ai-scripting/jsobjref/characterstyle" },
        { label: "CharacterStyles", link: "/ai-scripting/jsobjref/characterstyles" },
        { label: "CMYKColor", link: "/ai-scripting/jsobjref/cmykcolor" },
        { label: "Color", link: "/ai-scripting/jsobjref/color" },
        { label: "CompoundPathItem", link: "/ai-scripting/jsobjref/compoundpathitem" },
        { label: "CompoundPathItems", link: "/ai-scripting/jsobjref/compoundpathitems" },
        { label: "Dataset", link: "/ai-scripting/jsobjref/dataset" },
        { label: "Datasets", link: "/ai-scripting/jsobjref/datasets" },
        { label: "Document", link: "/ai-scripting/jsobjref/document" },
        { label: "DocumentPreset", link: "/ai-scripting/jsobjref/documentpreset" },
        { label: "Documents", link: "/ai-scripting/jsobjref/documents" },
        { label: "EPSSaveOptions", link: "/ai-scripting/jsobjref/epssaveoptions" },
        { label: "ExportOptionsAutoCAD", link: "/ai-scripting/jsobjref/exportoptionsautocad" },
        { label: "ExportOptionsFlash", link: "/ai-scripting/jsobjref/exportoptionsflash" },
        { label: "ExportOptionsGIF", link: "/ai-scripting/jsobjref/exportoptionsgif" },
        { label: "ExportOptionsJPEG", link: "/ai-scripting/jsobjref/exportoptionsjpeg" },
        { label: "ExportOptionsPhotoshop", link: "/ai-scripting/jsobjref/exportoptionsphotoshop" },
        { label: "ExportOptionsPNG24", link: "/ai-scripting/jsobjref/exportoptionspng24" },
        { label: "ExportOptionsPNG8", link: "/ai-scripting/jsobjref/exportoptionspng8" },
        { label: "ExportOptionsSVG", link: "/ai-scripting/jsobjref/exportoptionssvg" },
        { label: "ExportOptionsTIFF", link: "/ai-scripting/jsobjref/exportoptionstiff" },
        { label: "FXGSaveOptions", link: "/ai-scripting/jsobjref/fxgsaveoptions" },
        { label: "Gradient", link: "/ai-scripting/jsobjref/gradient" },
        { label: "GradientColor", link: "/ai-scripting/jsobjref/gradientcolor" },
        { label: "Gradients", link: "/ai-scripting/jsobjref/gradients" },
        { label: "GradientStop", link: "/ai-scripting/jsobjref/gradientstop" },
        { label: "GradientStops", link: "/ai-scripting/jsobjref/gradientstops" },
        { label: "GraphicStyle", link: "/ai-scripting/jsobjref/graphicstyle" },
        { label: "GraphicStyles", link: "/ai-scripting/jsobjref/graphicstyles" },
        { label: "GraphItem", link: "/ai-scripting/jsobjref/graphitem" },
        { label: "GraphItems", link: "/ai-scripting/jsobjref/graphitems" },
        { label: "GrayColor", link: "/ai-scripting/jsobjref/graycolor" },
        { label: "GroupItem", link: "/ai-scripting/jsobjref/groupitem" },
        { label: "GroupItems", link: "/ai-scripting/jsobjref/groupitems" },
        { label: "IllustratorSaveOptions", link: "/ai-scripting/jsobjref/illustratorsaveoptions" },
        { label: "ImageCaptureOptions", link: "/ai-scripting/jsobjref/imagecaptureoptions" },
        { label: "Ink", link: "/ai-scripting/jsobjref/ink" },
        { label: "InkInfo", link: "/ai-scripting/jsobjref/inkinfo" },
        { label: "InsertionPoint", link: "/ai-scripting/jsobjref/insertionpoint" },
        { label: "InsertionPoints", link: "/ai-scripting/jsobjref/insertionpoints" },
        { label: "LabColor", link: "/ai-scripting/jsobjref/labcolor" },
        { label: "Layer", link: "/ai-scripting/jsobjref/layer" },
        { label: "Layers", link: "/ai-scripting/jsobjref/layers" },
        { label: "LegacyTextItem", link: "/ai-scripting/jsobjref/legacytextitem" },
        { label: "LegacyTextItems", link: "/ai-scripting/jsobjref/legacytextitems" },
        { label: "Lines", link: "/ai-scripting/jsobjref/lines" },
        { label: "Matrix", link: "/ai-scripting/jsobjref/matrix" },
        { label: "MeshItem", link: "/ai-scripting/jsobjref/meshitem" },
        { label: "MeshItems", link: "/ai-scripting/jsobjref/meshitems" },
        { label: "NoColor", link: "/ai-scripting/jsobjref/nocolor" },
        { label: "NonNativeItem", link: "/ai-scripting/jsobjref/nonnativeitem" },
        { label: "NonNativeItems", link: "/ai-scripting/jsobjref/nonnativeitems" },
        { label: "OpenOptions", link: "/ai-scripting/jsobjref/openoptions" },
        { label: "OpenOptionsAutoCAD", link: "/ai-scripting/jsobjref/openoptionsautocad" },
        { label: "OpenOptionsFreeHand", link: "/ai-scripting/jsobjref/openoptionsfreehand" },
        { label: "OpenOptionsPhotoshop", link: "/ai-scripting/jsobjref/openoptionsphotoshop" },
        { label: "PageItem", link: "/ai-scripting/jsobjref/pageitem" },
        { label: "PageItems", link: "/ai-scripting/jsobjref/pageitems" },
        { label: "Paper", link: "/ai-scripting/jsobjref/paper" },
        { label: "PaperInfo", link: "/ai-scripting/jsobjref/paperinfo" },
        { label: "ParagraphAttributes", link: "/ai-scripting/jsobjref/paragraphattributes" },
        { label: "Paragraphs", link: "/ai-scripting/jsobjref/paragraphs" },
        { label: "ParagraphStyle", link: "/ai-scripting/jsobjref/paragraphstyle" },
        { label: "ParagraphStyles", link: "/ai-scripting/jsobjref/paragraphstyles" },
        { label: "PathItem", link: "/ai-scripting/jsobjref/pathitem" },
        { label: "PathItems", link: "/ai-scripting/jsobjref/pathitems" },
        { label: "PathPoint", link: "/ai-scripting/jsobjref/pathpoint" },
        { label: "PathPoints", link: "/ai-scripting/jsobjref/pathpoints" },
        { label: "Pattern", link: "/ai-scripting/jsobjref/pattern" },
        { label: "Patterns", link: "/ai-scripting/jsobjref/patterns" },
        { label: "PatternColor", link: "/ai-scripting/jsobjref/patterncolor" },
        { label: "PDFFileOptions", link: "/ai-scripting/jsobjref/pdffileoptions" },
        { label: "PDFSaveOptions", link: "/ai-scripting/jsobjref/pdfsaveoptions" },
        { label: "PhotoshopFileOptions", link: "/ai-scripting/jsobjref/photoshopfileoptions" },
        { label: "PlacedItem", link: "/ai-scripting/jsobjref/placeditem" },
        { label: "PlacedItems", link: "/ai-scripting/jsobjref/placeditems" },
        { label: "PluginItem", link: "/ai-scripting/jsobjref/pluginitem" },
        { label: "PluginItems", link: "/ai-scripting/jsobjref/pluginitems" },
        { label: "PPDFile", link: "/ai-scripting/jsobjref/ppdfile" },
        { label: "PPDFileInfo", link: "/ai-scripting/jsobjref/ppdfileinfo" },
        { label: "Preferences", link: "/ai-scripting/jsobjref/preferences" },
        { label: "PrintColorManagementOptions", link: "/ai-scripting/jsobjref/printcolormanagementoptions" },
        { label: "PrintColorSeparationOptions", link: "/ai-scripting/jsobjref/printcolorseparationoptions" },
        { label: "PrintCoordinateOptions", link: "/ai-scripting/jsobjref/printcoordinateoptions" },
        { label: "Printer", link: "/ai-scripting/jsobjref/printer" },
        { label: "PrinterInfo", link: "/ai-scripting/jsobjref/printerinfo" },
        { label: "PrintFlattenerOptions", link: "/ai-scripting/jsobjref/printflatteneroptions" },
        { label: "PrintFontOptions", link: "/ai-scripting/jsobjref/printfontoptions" },
        { label: "PrintJobOptions", link: "/ai-scripting/jsobjref/printjoboptions" },
        { label: "PrintOptions", link: "/ai-scripting/jsobjref/printoptions" },
        { label: "PrintPageMarksOptions", link: "/ai-scripting/jsobjref/printpagemarksoptions" },
        { label: "PrintPaperOptions", link: "/ai-scripting/jsobjref/printpaperoptions" },
        { label: "PrintPostScriptOptions", link: "/ai-scripting/jsobjref/printpostscriptoptions" },
        { label: "RasterEffectOptions", link: "/ai-scripting/jsobjref/rastereffectoptions" },
        { label: "RasterItem", link: "/ai-scripting/jsobjref/rasteritem" },
        { label: "RasterItems", link: "/ai-scripting/jsobjref/rasteritems" },
        { label: "RasterizeOptions", link: "/ai-scripting/jsobjref/rasterizeoptions" },
        { label: "RGBColor", link: "/ai-scripting/jsobjref/rgbcolor" },
        { label: "Screen", link: "/ai-scripting/jsobjref/screen" },
        { label: "ScreenInfo", link: "/ai-scripting/jsobjref/screeninfo" },
        { label: "ScreenSpotFunction", link: "/ai-scripting/jsobjref/screenspotfunction" },
        { label: "Spot", link: "/ai-scripting/jsobjref/spot" },
        { label: "SpotColor", link: "/ai-scripting/jsobjref/spotcolor" },
        { label: "Spots", link: "/ai-scripting/jsobjref/spots" },
        { label: "Story", link: "/ai-scripting/jsobjref/story" },
        { label: "Stories", link: "/ai-scripting/jsobjref/stories" },
        { label: "Swatch", link: "/ai-scripting/jsobjref/swatch" },
        { label: "Swatches", link: "/ai-scripting/jsobjref/swatches" },
        { label: "SwatchGroup", link: "/ai-scripting/jsobjref/swatchgroup" },
        { label: "SwatchGroups", link: "/ai-scripting/jsobjref/swatchgroups" },
        { label: "SymbolItem", link: "/ai-scripting/jsobjref/symbolitem" },
        { label: "SymbolItems", link: "/ai-scripting/jsobjref/symbolitems" },
        { label: "Symbol", link: "/ai-scripting/jsobjref/symbol" },
        { label: "Symbols", link: "/ai-scripting/jsobjref/symbols" },
        { label: "TabStopInfo", link: "/ai-scripting/jsobjref/tabstopinfo" },
        { label: "Tag", link: "/ai-scripting/jsobjref/tag" },
        { label: "Tags", link: "/ai-scripting/jsobjref/tags" },
        { label: "TextFont", link: "/ai-scripting/jsobjref/textfont" },
        { label: "TextFonts", link: "/ai-scripting/jsobjref/textfonts" },
        { label: "TextFrameItem", link: "/ai-scripting/jsobjref/textframeitem" },
        { label: "TextFrameItems", link: "/ai-scripting/jsobjref/textframeitems" },
        { label: "TextPath", link: "/ai-scripting/jsobjref/textpath" },
        { label: "TextRange", link: "/ai-scripting/jsobjref/textrange" },
        { label: "TextRanges", link: "/ai-scripting/jsobjref/textranges" },
        { label: "TracingObject", link: "/ai-scripting/jsobjref/tracingobject" },
        { label: "TracingOptions", link: "/ai-scripting/jsobjref/tracingoptions" },
        { label: "Variable", link: "/ai-scripting/jsobjref/variable" },
        { label: "Variables", link: "/ai-scripting/jsobjref/variables" },
        { label: "View", link: "/ai-scripting/jsobjref/view" },
        { label: "Views", link: "/ai-scripting/jsobjref/views" },
        { label: "Words", link: "/ai-scripting/jsobjref/words" },
      ],
    },
  ],
};
